### ISSUE TITLE
MPKNote Unix Timestamp wrong endianness

### ISSUE THREAD

**Issue by bryc** [HonkeyKong/Dexpedition64#3]
Hi there!

Pretty self-explanatory, the MPKNote format expects the byte order to be big-endian, but it's being stored as little-endian here. Basically the array should to be reversed when written to the output buffer.

**Comment by HonkeyKong** [comment]
Thanks for letting me know, I'll get that fixed ASAP. 😁

**Comment by HonkeyKong** [comment]
Fixed in latest commit.
